server:
  port: 7000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

spring:
  application:
    name: zipkin-server

zuul:
  routes:
    goods:
      path: /api-serviceA/**
      serviceId: SERVICEA
    ucenter:
      path: /api-serviceD/**
      serviceId: SERVICED
